project:
  type: website
  output-dir: docs/

website:
  title: "mattmajestic.io-dev"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: simplex
    toc: true

editor: visual

